server:
  port: 8082
  error:
    include-message: always

spring:
  application:
    name: trade-sales-api

  # Configuración Reactiva de Base de Datos (R2DBC)
  r2dbc:
    url: r2dbc:mysql://${DB_HOST:localhost}:3306/sales_db
    username: root
    password: root
    pool:
      initial-size: 10
      max-size: 20

  # Flyway (Solo JDBC para migraciones)
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    check-location: true # Esto te avisará en el log si no encuentra la carpeta
    url: jdbc:mysql://${DB_HOST:localhost}:3306/sales_db
    user: root
    password: root

  # Configuración de Jackson para manejar UUIDs y Fechas correctamente
  jackson:
    default-property-inclusion: non_null
    serialization:
      write_dates_as_timestamps: false
    date-format: yyyy-MM-dd HH:mm:ss

  # Configuración para que el generador de OpenAPI no choque con WebFlux
  main:
    web-application-type: reactive

# Kubernetes & Monitoring
management:
  endpoints:
    web:
      exposure:
        # Exponemos prometheus para métricas y health para K8s
        include: health,info,metrics,prometheus
  endpoint:
    health:
      # Muestra detalles como conexión a BD (R2DBC) y espacio en disco
      show-details: always
      probes:
        # Esto genera las rutas /actuator/health/liveness y /actuator/health/readiness
        enabled: true # Crucial para K8s (Liveness/Readiness)
# Configuración de SpringDoc (Swagger UI) para ver los contratos separados
springdoc:
  show-actuator: true # Para que los endpoints de salud aparezcan en tu Swagger
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    # Esto permite elegir qué contrato ver en el desplegable de Swagger
    groups-order: ASC
    display-query-params-view: true
  # Definición de los grupos basados en tus archivos YAML
  group-config:
    - group: 1-catalog
      display-name: "Catálogo e Inventario"
      paths-to-match: /api/v1/products/**, /api/v1/categories/**, /api/v1/inventory/**
    - group: 2-sales
      display-name: "Ventas y Clientes"
      paths-to-match: /api/v1/sales/**, /api/v1/customers/**
    - group: 3-users
      display-name: "Usuarios y Seguridad"
      paths-to-match: /api/v1/users/**, /api/v1/auth/**
    - group: 4-audit
      display-name: "Auditoría de Sistema"
      paths-to-match: /api/v1/audit/**
jwt:
  secret: ${JWT_SECRET:v9y$B&E)H@McQfTjWnZr4u7x!A%C*F-JaNdRgUkXp2s5v8y/B?E(G+KbPeShVmYq}
  #expiration: 900000 #15 minutos en milisegundos
  expiration: 120000 #2 minutos en milisegundos
# Logs para debugging de SQL Reactivo
logging:
  level:
    org.springframework.r2dbc: DEBUG
    io.asyncer.r2dbc.mysql: DEBUG