apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sales-jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
        - name: jenkins
          image: diegosantos95/sales-jenkins:latest
          imagePullPolicy: Always # En PROD siempre queremos la versión oficial del registro
          env:
            - name: DOCKER_HOST
              value: tcp://localhost:2375 # Jenkins buscará a Docker en la red interna del Pod
          ports:
            - containerPort: 8080
            - containerPort: 50000
          volumeMounts:
            - name: jenkins-data
              mountPath: /var/jenkins_home

        # EL INTEGRANTE DE PROD: Contenedor Sidecar de Docker
        - name: dind
          image: docker:dind
          privileged: true
          env:
            - name: DOCKER_TLS_CERTDIR
              value: "" # Deshabilitamos TLS para simplificar comunicación interna en el Pod
          volumeMounts:
            - name: jenkins-data
              mountPath: /var/jenkins_home

      volumes:
        - name: jenkins-data
          persistentVolumeClaim:
            claimName: jenkins-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: sales-jenkins
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 8083
      targetPort: 8080
    - name: agent
      port: 50000
      targetPort: 50000
  selector:
    app: jenkins