#Expone tu API internamente o hacia afuera del clúster (usando un LoadBalancer o NodePort).
apiVersion: v1
kind: Service
metadata:
  name: sales-api-service
spec:
  selector:
    app: sales-api
  ports:
    - name: http-web
      protocol: TCP
      port: 80          # Puerto de entrada tambien puede ser 8082 http://localhost/swagger-ui/index.html
      targetPort: 8082  # ¡Debe ser el mismo que el port-forward! # Puerto donde corre tu app Spring Boot
  #type: NodePort # Para acceder localmente en Minikube o Docker Desktop
    - name: http-metrics  # <--- IMPORTANTE: Ponle nombre al puerto
      protocol: TCP
      port: 8082
      targetPort: 8082
  type: LoadBalancer   # En Docker Desktop, esto suele ser más estable que NodePort